openapi: 3.0.0
info:
  title: Bat API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1

#servers:
#  - url: http://api.example.com/v1
#    description: Optional server description, e.g. Main (production) server
#  - url: http://staging-api.example.com
#    description: Optional server description, e.g. Internal staging server for testing

paths:
  /hello_world:
    get:
        summary: returns "Hello world!"
        description: Example API endpoint
        operationId: bat.lib.hello_world
        responses:
            '200':
                description: OK

  /temperature:
    get:
        summary: returns temperature record
        description: Return the temperature record for a given location
        operationId: bat.lib.get_temperature
        responses:
            '200':
                description: OK

  /presure:
    get:
        summary: returns presure record
        description: Return the presure record for a given location
        operationId: bat.lib.get_presure
        responses:
            '200':
                description: OK

  /wind:
    get:
        summary: returns wind record
        description: Return the wind record for a given location
        operationId: bat.lib.get_wind
        responses:
            '200':
                description: OK
